/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/* 
 * File: Pressure_13.h
 * Author: C65471
 * Comments:
 * Revision history: 
 */

#ifndef PRESSURE_13_H
#define	PRESSURE_13_H

#include <xc.h>
#include "mcc_generated_files/system/system.h"
#include <math.h>


#ifdef	__cplusplus
extern "C" {
#endif

//#define PRESSURE_SENSOR_A_TERM  0.0046 //0.00293 on datasheet, recalculated for application
#define PRESSURE_SENSOR_A_TERM 0.00293
#define PRESSURE_SENSOR_B_TERM  0.05069
#define ADCC_RESOLUTION         4096
#define ADCC_POS_REFERENCE      5.00
#define SENSOR_VDD              5.00
    

    // Function Declarations;
    //void PRESSURE_13_ADCC_Init(void);
    //void PRESSURE_OPA_Disable(void);
    //void PRESSURE_13_FVR_Init(void);
    void PRESSURE_13_Init(void);
    void PRESSURE_13_SendData(void);

#ifdef	__cplusplus
}
#endif

#endif	/* PRESSURE_13_H */

